set(CROSS_ROOTFS $ENV{ROOTFS_DIR})

add_definitions(-D_TARGET_ARM64_ -D_TARGET_64BIT_ -D_ARM64_ -DARM64 -D_WIN64 -DBIT64 -DLINUX64)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

## Specify the toolchain
set(TOOLCHAIN "aarch64-tizen-linux-gnu")
set(TOOLCHAIN_PREFIX ${TOOLCHAIN}-)

if ("$ENV{CC}" MATCHES "lang")
    add_compile_options(-target aarch64-tizen-linux-gnu)
endif()
add_compile_options(--sysroot=${CROSS_ROOTFS})

if (DEFINED ENV{ENV_GCC_LIB_PATH})
    set(GCC_LIB_PATH $ENV{ENV_GCC_LIB_PATH})
else()
    set(GCC_LIB_PATH /usr/lib64/gcc/${TOOLCHAIN}/9.2.0)
endif()

if ("$ENV{CC}" MATCHES "lang")
    set(CROSS_LINK_FLAGS "${CROSS_LINK_FLAGS} -target aarch64-linux-gnu")
    set(CROSS_LINK_FLAGS "${CROSS_LINK_FLAGS} -B${CROSS_ROOTFS}${GCC_LIB_PATH}")
endif()
set(CROSS_LINK_FLAGS "${CROSS_LINK_FLAGS} -L${CROSS_ROOTFS}${GCC_LIB_PATH}")
set(CROSS_LINK_FLAGS "${CROSS_LINK_FLAGS} --sysroot=${CROSS_ROOTFS}")

set(CMAKE_EXE_LINKER_FLAGS    "${CMAKE_EXE_LINKER_FLAGS}    ${CROSS_LINK_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${CROSS_LINK_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} ${CROSS_LINK_FLAGS}" CACHE STRING "" FORCE)

set(CMAKE_FIND_ROOT_PATH "${CROSS_ROOTFS}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
